SalmonBridges:
  - SBName: "salmon-bridge-test"
    SBSocksListenPort: 1080
    SBHttpListenPort: 8080
    SBConnect: true
    SBFarPort: 55001
    SBFarIp: "127.0.0.1"
    SBIdleTimeout: 10s
    SBInitialPacketSize: 8400
    SBRecieveWindow: 100M
    SBMaxRecieveWindow: 400M
    SBTotalBandwidthLimit: 700M
