ApiConfig:
  Hostname: "localhost"
  Port: 8081

SocksRedirect:
  Hostname: "localhost"
  Port: 8082
  Redirects:
    "example.com": "bridge-one"
    "example.org": "bridge-two"

GlobalLog:
  Filename: "sc.log"
  MaxSize: 20        # megabytes
  MaxBackups: 5
  MaxAge: 28         # days
  Compress: false

SalmonBridges:
  - SBName: "salmon-bridge-1-connect-minimal"
    SBSocksListenPort: 1080
    SBConnect: true
    SBFarPort: 55001
    SBFarIp: "far-ip-here"
  - SBName: "salmon-bridge-1-accept-minimal"
    SBConnect: false
    SBNearPort: 55001
  - SBName: "salmon-bridge-1-connect-full"
    SBSocksListenPort: 1080
    SBConnect: true
    SBNearPort: 55001
    SBFarIp: "far-ip-here"
    SBHttpListenPort: 8080
    SBSocksListenAddress: "127.0.0.1"
    SBIdleTimeout: 1m
    SBInitialPacketSize: 1350
    SBTotalBandwidthLimit: 100M
    SBMaxRecieveBufferSize: 2GB
    SBInterfaceName: "eth0"
    SBAllowedInAddresses:
      - "127.0.0.1"
      - "127.0.0.2"
    SBAllowedOutAddresses:
      - "example.com"
      - "example2.com"
  - SBName: "salmon-bridge-2-accept-full"
    SBSocksListenPort: 1081
    SBConnect: false
    SBNearPort: 55002
    SBIdleTimeout: 1m
    SBInitialPacketSize: 1350
    SBTotalBandwidthLimit: 100M
    SBMaxRecieveBufferSize: 2GB
    SBInterfaceName: "eth0"
    SBAllowedInAddresses:
      - "127.0.0.1"
      - "127.0.0.2"
    SBAllowedOutAddresses:
      - "example.com"
      - "example2.com"